import Card from "../components/Card";
import Loading from "../components/Loading";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
const apikey = `b47d4f0eeb9a4a389c2bc3a4613ae3ae`;

export async function getServerSideProps() {
  const res = await fetch(
    `https://newsapi.org/v2/top-headlines?country=us&apiKey=${apikey}`
  );
  const { articles } = await res.json();

  return {
    props: { articles: articles },
  };
}

export default function Home({ articles }) {
  return (
    <div>
      {console.log(articles)}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="news">
        {articles.length > 0 &&
          articles.map((article) => {
            return (
              <div key={article.url}>
                <Card
                  author={article.author}
                  title={article.title}
                  imageUrl={article.url}
                />
              </div>
            );
          })}

        {articles.length === 0 && <Loading />}
      </div>
    </div>
  );
}
