import Card from "../components/Card";
import Loading from "../components/Loading";
import Header from "../components/Header";
import Chip from "@mui/material/Chip";
import Stack from "@mui/material/Stack";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
const apikey = `b47d4f0eeb9a4a389c2bc3a4613ae3ae`;

export default function Home() {
  const [articles, setArticles] = useState([]);
  const [country, setCountry] = useState("us");
  const [category, setCategory] = useState("general");

  const data = [
    { code: "br", label: "brazil" },
    { code: "id", label: "indonesia" },
    { code: "us", label: "united states" },
    { code: "au", label: "australia" },
    { code: "ae", label: "saudi arabia" },
    { code: "cn", label: "china" },
    { code: "sg", label: "singapore" },
  ];
  const kategori = [
    { code: "general" },
    { code: "business" },
    { code: "entertainment" },
    { code: "health" },
    { code: "science" },
    { code: "sports" },
    { code: "technology" },
  ];

  useEffect(() => {
    fetchData();
  }, [country, category]);

  const fetchData = async () => {
    const res = await fetch(
      `https://newsapi.org/v2/top-headlines?pageSize=21&country=${country}&category=${category}&apiKey=${process.env.NEXT_PUBLIC_MY_API_KEY}`
    );
    const { articles } = await res.json();
    setArticles(articles);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Stack className="chip" direction="row" spacing={1}>
        {data.map((dat, index) => {
          return (
            <Chip
              key={index}
              label={dat.label}
              variant="outlined"
              onClick={() => {
                setCountry(dat.code), console.log(country);
              }}
            />
          );
        })}
      </Stack>

      <Stack className="chip" direction="row" spacing={1}>
        {kategori.map((dat, index) => {
          return (
            <Chip
              key={index}
              label={dat.code}
              onClick={() => {
                setCategory(dat.code);
              }}
            />
          );
        })}
      </Stack>

      <div className="news">
        {articles.length > 0 &&
          articles.map((article) => {
            return (
              <div className="card" key={article.url}>
                <Card
                  author={article.author}
                  title={article.title}
                  imageUrl={article.urlToImage}
                  url={article.url}
                  description={article.description}
                  date={article.publishedAt}
                />
              </div>
            );
          })}

        {articles.length === 0 && <Loading />}
      </div>
    </div>
  );
}
